### ISSUE TITLE
فریز شدن برنامه

### ISSUE THREAD

**Issue by b3hzad1** [hossein-mohseni/EP-Scanner#7]
در نسخه جدید (0.4) در مرحله Testing ON Warp-plus... [6s] متاسفانه برنامه فریز میکنه مثلاً روی 6 ثانیه گیر میکنه و دیگه ادامه نمیده. با نسخه قبلی (v 0.2) این مشکل رو ندارم. احتمالاً به دلیل زیاد شدن تعداد IPهایی هست که باید چک بشه.

**Comment by hossein-mohseni** [comment]
> در نسخه جدید (0.4) در مرحله Testing ON Warp-plus... [6s] متاسفانه برنامه فریز میکنه مثلاً روی 6 ثانیه گیر میکنه و دیگه ادامه نمیده. با نسخه قبلی (v 0.2) این مشکل رو ندارم. احتمالاً به دلیل زیاد شدن تعداد IPهایی هست که باید چک بشه.

بله درسته توی نسخه ی جدید همراه با اپدیت شدن warp plus حتما این موضوع رو بررسی و‌ رفع میکنم🌹
